name: 'OSV'
on:
  workflow_dispatch:

permissions:
  contents: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  osv-detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check dependencies for security vulnerabilities
        continue-on-error: true
        uses: g-rath/check-with-osv-detector@main
        id: osvcheck
        with:
          flags: -json
      
      - name: Insight of results
        run: |
          echo "${{ steps.osvcheck.outputs.json }}" > osv.json
      
      - name: Archive osv results
        uses: actions/upload-artifact@v3
        with:
          name: osv-report
          path: osv.json
          if-no-files-found: ignore
  
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
      
      - name: check go version
        id: osvscan
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1
          export PATH=${PATH}:`go env GOPATH`/bin
          osv-scanner --json -r . >> $GITHUB_OUTPUT
          
      - name: Insight of results
        run: |
          echo "${{ steps.osvscan.outputs.json }}" > osvscan.json 
      
      - name: Archive osv results
        uses: actions/upload-artifact@v3
        with:
          name: osv-report
          path: osvscan.json
          if-no-files-found: ignore
          
          


