name: 'OSV'
on:
  workflow_dispatch:

permissions:
  contents: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  sca-scan:
    name: sca osv scanner google
    runs-on: ubuntu-latest
    steps:
      - name: gets sources
        uses: actions/checkout@v3.2.0
      - name: gets osv
        uses: google/osv-scanner@latest

