  sca-scan:
    name: sca osv scanner google
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
      - name: gets the osv scanner repo
        uses: actions/checkout@v3.2.0
        with:
          repository: google/osv-scanner
