name: 'SBOM Check'
on:
  workflow_dispatch:

permissions:
  contents: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout
      - name: Checkout
        uses: actions/checkout@v3
    
    # Create SBOM
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.13.1
        with:
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
    
    # Scan SBOM
      - name: Anchore Container Scan
        uses: anchore/scan-action@v3.3.2
        id: scan
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: "false"
          severity-cutoff: negligible
          
      - name: upload Anchore scan SARIF report
        uses: actions/upload-artifact@v3.1.1
        with:
          path: ${{ steps.scan.outputs.sarif }}
      
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
          
#  legal:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run GitHub Action for ORT
#        uses: oss-review-toolkit/ort-ci-github-action@v1
